kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: node:12.16.3
    commands:
      - npm config set registry http://registry.npm.taobao.org
      - npm install -silent
      - npm run build
  - name: develop deploy main
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: host
      port:
        from_secret: port
      username:
        from_secret: username
      password:
        from_secret: password
      target:
        from_secret: target
      source: ./dist
      rm: true
    when:
      branch:
        - deploy_develop
        - deploy_release
trigger:
  branch:
    - deploy_develop
    - deploy_release