// 常用正则表达式
export default {
  Email: /\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*/,
  Account: /^[a-zA-Z0-9_]{2,20}$/,
  Password: /^[a-zA-Z0-9_~!@#$%^&*()]{6,25}$/i,
  Phone: /^(0\d{2,3}-)?\d{7,8}$/,
  Mobile: /^1[3-9][0-9]{9}$/,
  IDCard: /^\d{17}[\d|X|x]|\d{15}$/,
  Number: /^\d+$/,
  Integer: /^[-+]?\d+$/,
  IntegerZ: /^[1-9]\d*$/,
  IntegerF: /^-[1-9]\d*$/,
  Chinese: /^[\u0391-\uFFE5]+$/,
  Zipcode: /^\d{6}$/,
  Authcode: /^\d{6}$/,
  QQ: /^\d{4,12}$/,
  Price: /^(0|[1-9]\d*)(\.\d{1,2})?$/,
  Money: /^(0|[1-9]\d*)(\.\d{1,4})?$/,
  Distance: /^(0|[1-9]\d*)(\.\d{1,3})?$/,
  Letter: /^[A-Za-z]+$/,
  LetterU: /^[A-Z]+$/,
  LetterL: /^[a-z]+$/,
  Url: /^(https|http)?:\/\/[A-Za-z0-9-_]+\.[A-Za-z0-9]+[/=?%\-&_~`@[\]':+!]*([^<>""])*$/,
  Date: /^\d{4}(-|\/|\.)\d{1,2}\1\d{1,2}$/,
  Domain: /^[a-zA-Z0-9]{4,}$/,
  Version: /^(\d+\.){1,3}\d+$/,
};
